version: '3.8'

services:
  nginx:
    container_name: wallets-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8002:80"
    working_dir: /var/www/web-wallets
    volumes:
      - ./:/var/www/web-wallets
      - ./docker/nginx/:/etc/nginx/conf.d/
  php:
    container_name: wallets-php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /var/www/web-wallets
    volumes:
      - .:/var/www/web-wallets
      - /var/www/web-wallets/vendor
  postgres:
    container_name: wallets-postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres/database:/var/lib/postgresql/data
      - ./docker/postgres/dumps:/docker-entrypoint-initdb.d/
  redis:
    container_name: wallets-redis
    image: redis:alpine
    restart: always
    ports:
      - "63379:6379"
